package PIM.WEBSERIVE.ACTIVITIE.STUDENT.Model;
// default package
// Generated 22 �.�. 2561, 22:56:21 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Activitie generated by hbm2java
 */
@Entity
@Table(name = "activitie", catalog = "panyapiway_student_activitie")
public class Activitie implements java.io.Serializable {

	private Long id;
	private Account account;
	private ActivitieType activitieType;
	private StudentHaveDutyByYearClassQuarter studentHaveDutyByYearClassQuarter;
	private String status;
	private Date dateTime;
	private int duration;
	private String location;
	private String hearder;
	private String detail;
	private Integer allowance;
	private String responsibleAgency;
	private String holderActivitieName;
	private String holderActivitiePhone;
	private String holderActivitieEmail;
	private Date createDate;
	private Set<ImageActivitie> imageActivities = new HashSet<ImageActivitie>(0);

	public Activitie() {
	}

	public Activitie(ActivitieType activitieType, StudentHaveDutyByYearClassQuarter studentHaveDutyByYearClassQuarter,
			Date dateTime, int duration, String detail) {
		this.activitieType = activitieType;
		this.studentHaveDutyByYearClassQuarter = studentHaveDutyByYearClassQuarter;
		this.dateTime = dateTime;
		this.duration = duration;
		this.detail = detail;
	}

	public Activitie(Account account, ActivitieType activitieType,
			StudentHaveDutyByYearClassQuarter studentHaveDutyByYearClassQuarter, String status, Date dateTime,
			int duration, String location, String hearder, String detail, Integer allowance, String responsibleAgency,
			String holderActivitieName, String holderActivitiePhone, String holderActivitieEmail, Date createDate,
			Set<ImageActivitie> imageActivities) {
		this.account = account;
		this.activitieType = activitieType;
		this.studentHaveDutyByYearClassQuarter = studentHaveDutyByYearClassQuarter;
		this.status = status;
		this.dateTime = dateTime;
		this.duration = duration;
		this.location = location;
		this.hearder = hearder;
		this.detail = detail;
		this.allowance = allowance;
		this.responsibleAgency = responsibleAgency;
		this.holderActivitieName = holderActivitieName;
		this.holderActivitiePhone = holderActivitiePhone;
		this.holderActivitieEmail = holderActivitieEmail;
		this.createDate = createDate;
		this.imageActivities = imageActivities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "verify_by_account_id")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "activitie_type_id", nullable = false)
	public ActivitieType getActivitieType() {
		return this.activitieType;
	}

	public void setActivitieType(ActivitieType activitieType) {
		this.activitieType = activitieType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_have_duty_by_year_class_quarter_id", nullable = false)
	public StudentHaveDutyByYearClassQuarter getStudentHaveDutyByYearClassQuarter() {
		return this.studentHaveDutyByYearClassQuarter;
	}

	public void setStudentHaveDutyByYearClassQuarter(
			StudentHaveDutyByYearClassQuarter studentHaveDutyByYearClassQuarter) {
		this.studentHaveDutyByYearClassQuarter = studentHaveDutyByYearClassQuarter;
	}

	@Column(name = "status", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_time", nullable = false, length = 19)
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "duration", nullable = false)
	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	@Column(name = "location", length = 300)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "hearder", length = 150)
	public String getHearder() {
		return this.hearder;
	}

	public void setHearder(String hearder) {
		this.hearder = hearder;
	}

	@Column(name = "detail", nullable = false, length = 200)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "allowance")
	public Integer getAllowance() {
		return this.allowance;
	}

	public void setAllowance(Integer allowance) {
		this.allowance = allowance;
	}

	@Column(name = "responsible_agency", length = 60)
	public String getResponsibleAgency() {
		return this.responsibleAgency;
	}

	public void setResponsibleAgency(String responsibleAgency) {
		this.responsibleAgency = responsibleAgency;
	}

	@Column(name = "holder_activitie_name", length = 150)
	public String getHolderActivitieName() {
		return this.holderActivitieName;
	}

	public void setHolderActivitieName(String holderActivitieName) {
		this.holderActivitieName = holderActivitieName;
	}

	@Column(name = "holder_activitie_phone", length = 13)
	public String getHolderActivitiePhone() {
		return this.holderActivitiePhone;
	}

	public void setHolderActivitiePhone(String holderActivitiePhone) {
		this.holderActivitiePhone = holderActivitiePhone;
	}

	@Column(name = "holder_activitie_email", length = 100)
	public String getHolderActivitieEmail() {
		return this.holderActivitieEmail;
	}

	public void setHolderActivitieEmail(String holderActivitieEmail) {
		this.holderActivitieEmail = holderActivitieEmail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activitie")
	public Set<ImageActivitie> getImageActivities() {
		return this.imageActivities;
	}

	public void setImageActivities(Set<ImageActivitie> imageActivities) {
		this.imageActivities = imageActivities;
	}

}
