package PIM.WEBSERIVE.ACTIVITIE.STUDENT.Model;
// default package
// Generated 22 �.�. 2561, 22:56:21 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "panyapiway_student_activitie")
public class Address implements java.io.Serializable {

	private Long id;
	private Person person;
	private String houseNo;
	private String villageNo;
	private String alley;
	private String lane;
	private String road;
	private String subDistrict;
	private String district;
	private String province;
	private int postalCode;

	public Address() {
	}

	public Address(Person person, String province, int postalCode) {
		this.person = person;
		this.province = province;
		this.postalCode = postalCode;
	}

	public Address(Person person, String houseNo, String villageNo, String alley, String lane, String road,
			String subDistrict, String district, String province, int postalCode) {
		this.person = person;
		this.houseNo = houseNo;
		this.villageNo = villageNo;
		this.alley = alley;
		this.lane = lane;
		this.road = road;
		this.subDistrict = subDistrict;
		this.district = district;
		this.province = province;
		this.postalCode = postalCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "person_id", nullable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "house_no", length = 10)
	public String getHouseNo() {
		return this.houseNo;
	}

	public void setHouseNo(String houseNo) {
		this.houseNo = houseNo;
	}

	@Column(name = "village_no", length = 10)
	public String getVillageNo() {
		return this.villageNo;
	}

	public void setVillageNo(String villageNo) {
		this.villageNo = villageNo;
	}

	@Column(name = "alley", length = 10)
	public String getAlley() {
		return this.alley;
	}

	public void setAlley(String alley) {
		this.alley = alley;
	}

	@Column(name = "lane", length = 30)
	public String getLane() {
		return this.lane;
	}

	public void setLane(String lane) {
		this.lane = lane;
	}

	@Column(name = "road", length = 30)
	public String getRoad() {
		return this.road;
	}

	public void setRoad(String road) {
		this.road = road;
	}

	@Column(name = "sub_district", length = 50)
	public String getSubDistrict() {
		return this.subDistrict;
	}

	public void setSubDistrict(String subDistrict) {
		this.subDistrict = subDistrict;
	}

	@Column(name = "district", length = 50)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "province", nullable = false, length = 50)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "postal_code", nullable = false)
	public int getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(int postalCode) {
		this.postalCode = postalCode;
	}

}
