package PIM.WEBSERIVE.ACTIVITIE.STUDENT.Model;
// default package
// Generated 22 �.�. 2561, 22:56:21 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Duty generated by hbm2java
 */
@Entity
@Table(name = "duty", catalog = "panyapiway_student_activitie")
public class Duty implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<StudentHaveDuty> studentHaveDuties = new HashSet<StudentHaveDuty>(0);
	private Set<News> newses = new HashSet<News>(0);
	private Set<InfoActivitie> infoActivities = new HashSet<InfoActivitie>(0);

	public Duty() {
	}

	public Duty(String name) {
		this.name = name;
	}

	public Duty(String name, Set<StudentHaveDuty> studentHaveDuties, Set<News> newses,
			Set<InfoActivitie> infoActivities) {
		this.name = name;
		this.studentHaveDuties = studentHaveDuties;
		this.newses = newses;
		this.infoActivities = infoActivities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "duty")
	public Set<StudentHaveDuty> getStudentHaveDuties() {
		return this.studentHaveDuties;
	}

	public void setStudentHaveDuties(Set<StudentHaveDuty> studentHaveDuties) {
		this.studentHaveDuties = studentHaveDuties;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "duty")
	public Set<News> getNewses() {
		return this.newses;
	}

	public void setNewses(Set<News> newses) {
		this.newses = newses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "duty")
	public Set<InfoActivitie> getInfoActivities() {
		return this.infoActivities;
	}

	public void setInfoActivities(Set<InfoActivitie> infoActivities) {
		this.infoActivities = infoActivities;
	}

}
