package PIM.WEBSERIVE.ACTIVITIE.STUDENT.Model;
// default package
// Generated 22 �.�. 2561, 22:56:21 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ImageActivitie generated by hbm2java
 */
@Entity
@Table(name = "image_activitie", catalog = "panyapiway_student_activitie")
public class ImageActivitie implements java.io.Serializable {

	private Long id;
	private Activitie activitie;
	private String name;

	public ImageActivitie() {
	}

	public ImageActivitie(Activitie activitie) {
		this.activitie = activitie;
	}

	public ImageActivitie(Activitie activitie, String name) {
		this.activitie = activitie;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "activitie_id", nullable = false)
	public Activitie getActivitie() {
		return this.activitie;
	}

	public void setActivitie(Activitie activitie) {
		this.activitie = activitie;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
