package PIM.WEBSERIVE.ACTIVITIE.STUDENT.Model;
// default package
// Generated 22 �.�. 2561, 22:56:21 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InfoActivitieHasAccountId generated by hbm2java
 */
@Embeddable
public class InfoActivitieHasAccountId implements java.io.Serializable {

	private long infoActivitieId;
	private long accountId;

	public InfoActivitieHasAccountId() {
	}

	public InfoActivitieHasAccountId(long infoActivitieId, long accountId) {
		this.infoActivitieId = infoActivitieId;
		this.accountId = accountId;
	}

	@Column(name = "info_activitie_id", nullable = false)
	public long getInfoActivitieId() {
		return this.infoActivitieId;
	}

	public void setInfoActivitieId(long infoActivitieId) {
		this.infoActivitieId = infoActivitieId;
	}

	@Column(name = "account_id", nullable = false)
	public long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(long accountId) {
		this.accountId = accountId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InfoActivitieHasAccountId))
			return false;
		InfoActivitieHasAccountId castOther = (InfoActivitieHasAccountId) other;

		return (this.getInfoActivitieId() == castOther.getInfoActivitieId())
				&& (this.getAccountId() == castOther.getAccountId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getInfoActivitieId();
		result = 37 * result + (int) this.getAccountId();
		return result;
	}

}
