package PIM.WEBSERIVE.ACTIVITIE.STUDENT.Model;
// default package

// Generated 22 �.�. 2561, 22:56:21 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * Major generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "major", catalog = "panyapiway_student_activitie", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Major implements java.io.Serializable {

	private int id;
	@JsonSerialize(as = Faculty.class)
	private Faculty faculty;
	private String name;
	@JsonIgnore
	private Set<Student> students = new HashSet<Student>(0);

	public Major() {
	}

	public Major(int id, Faculty faculty) {
		this.id = id;
		this.faculty = faculty;
	}

	public Major(int id, Faculty faculty, String name, Set<Student> students) {
		this.id = id;
		this.faculty = faculty;
		this.name = name;
		this.students = students;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "faculty_id", nullable = false)
	public Faculty getFaculty() {
		return this.faculty;
	}

	public void setFaculty(Faculty faculty) {
		this.faculty = faculty;
	}

	@Column(name = "name", unique = true, length = 60)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "major")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
