package PIM.WEBSERIVE.ACTIVITIE.STUDENT.Model;
// default package
// Generated 22 �.�. 2561, 22:56:21 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MessageHasAccount generated by hbm2java
 */
@Entity
@Table(name = "message_has_account", catalog = "panyapiway_student_activitie")
public class MessageHasAccount implements java.io.Serializable {

	private MessageHasAccountId id;
	private Account account;
	private Message message;
	private String status;
	private Date updateDate;

	public MessageHasAccount() {
	}

	public MessageHasAccount(MessageHasAccountId id, Account account, Message message) {
		this.id = id;
		this.account = account;
		this.message = message;
	}

	public MessageHasAccount(MessageHasAccountId id, Account account, Message message, String status, Date updateDate) {
		this.id = id;
		this.account = account;
		this.message = message;
		this.status = status;
		this.updateDate = updateDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "messageId", column = @Column(name = "message_id", nullable = false)),
			@AttributeOverride(name = "accountId", column = @Column(name = "account_id", nullable = false)) })
	public MessageHasAccountId getId() {
		return this.id;
	}

	public void setId(MessageHasAccountId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false, insertable = false, updatable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "message_id", nullable = false, insertable = false, updatable = false)
	public Message getMessage() {
		return this.message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

	@Column(name = "status", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
