package PIM.WEBSERIVE.ACTIVITIE.STUDENT.Model;
// default package
// Generated 22 �.�. 2561, 22:56:21 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * News generated by hbm2java
 */
@Entity
@Table(name = "news", catalog = "panyapiway_student_activitie")
public class News implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Duty duty;
	private Date createDate;
	private String hearder;
	private String detail;

	public News() {
	}

	public News(Account account, Duty duty, String hearder, String detail) {
		this.account = account;
		this.duty = duty;
		this.hearder = hearder;
		this.detail = detail;
	}

	public News(Account account, Duty duty, Date createDate, String hearder, String detail) {
		this.account = account;
		this.duty = duty;
		this.createDate = createDate;
		this.hearder = hearder;
		this.detail = detail;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "create_by_account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "duty_id", nullable = false)
	public Duty getDuty() {
		return this.duty;
	}

	public void setDuty(Duty duty) {
		this.duty = duty;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "hearder", nullable = false, length = 60)
	public String getHearder() {
		return this.hearder;
	}

	public void setHearder(String hearder) {
		this.hearder = hearder;
	}

	@Column(name = "detail", nullable = false, length = 200)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

}
