package PIM.WEBSERIVE.ACTIVITIE.STUDENT.Model;
// default package
// Generated 22 �.�. 2561, 22:56:21 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person", catalog = "panyapiway_student_activitie")
public class Person implements java.io.Serializable {

	private long id;
	private String firstName;
	private String lastName;
	private Date birthDate;
	private Long picture;
	private Set<Address> addresses = new HashSet<Address>(0);
	private Set<Account> accounts = new HashSet<Account>(0);
	private Set<Email> emails = new HashSet<Email>(0);
	private Set<Phone> phones = new HashSet<Phone>(0);
	private Set<Student> studentsForPersonId = new HashSet<Student>(0);
	private Set<Student> studentsForAdviserId = new HashSet<Student>(0);

	public Person() {
	}

	public Person(long id, String firstName, String lastName, Date birthDate) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.birthDate = birthDate;
	}

	public Person(long id, String firstName, String lastName, Date birthDate, Long picture, Set<Address> addresses,
			Set<Account> accounts, Set<Email> emails, Set<Phone> phones, Set<Student> studentsForPersonId,
			Set<Student> studentsForAdviserId) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.birthDate = birthDate;
		this.picture = picture;
		this.addresses = addresses;
		this.accounts = accounts;
		this.emails = emails;
		this.phones = phones;
		this.studentsForPersonId = studentsForPersonId;
		this.studentsForAdviserId = studentsForAdviserId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "first_name", nullable = false, length = 60)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 60)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birth_date", nullable = false, length = 10)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "picture")
	public Long getPicture() {
		return this.picture;
	}

	public void setPicture(Long picture) {
		this.picture = picture;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "person")
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "person")
	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "person")
	public Set<Email> getEmails() {
		return this.emails;
	}

	public void setEmails(Set<Email> emails) {
		this.emails = emails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "person")
	public Set<Phone> getPhones() {
		return this.phones;
	}

	public void setPhones(Set<Phone> phones) {
		this.phones = phones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personByPersonId")
	public Set<Student> getStudentsForPersonId() {
		return this.studentsForPersonId;
	}

	public void setStudentsForPersonId(Set<Student> studentsForPersonId) {
		this.studentsForPersonId = studentsForPersonId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personByAdviserId")
	public Set<Student> getStudentsForAdviserId() {
		return this.studentsForAdviserId;
	}

	public void setStudentsForAdviserId(Set<Student> studentsForAdviserId) {
		this.studentsForAdviserId = studentsForAdviserId;
	}

}
