package PIM.WEBSERIVE.ACTIVITIE.STUDENT.Model;
// default package
// Generated 22 �.�. 2561, 22:56:21 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StudentHaveDutyByYearClassQuarter generated by hbm2java
 */
@Entity
@Table(name = "student_have_duty_by_year_class_quarter", catalog = "panyapiway_student_activitie")
public class StudentHaveDutyByYearClassQuarter implements java.io.Serializable {

	private Long id;
	private Quarter quarter;
	private StudentHaveDutyByYearClass studentHaveDutyByYearClass;
	private Integer canDo;
	private Integer averagePerQuarter;
	private String status;
	private Set<Activitie> activities = new HashSet<Activitie>(0);

	public StudentHaveDutyByYearClassQuarter() {
	}

	public StudentHaveDutyByYearClassQuarter(Quarter quarter, StudentHaveDutyByYearClass studentHaveDutyByYearClass) {
		this.quarter = quarter;
		this.studentHaveDutyByYearClass = studentHaveDutyByYearClass;
	}

	public StudentHaveDutyByYearClassQuarter(Quarter quarter, StudentHaveDutyByYearClass studentHaveDutyByYearClass,
			Integer canDo, Integer averagePerQuarter, String status, Set<Activitie> activities) {
		this.quarter = quarter;
		this.studentHaveDutyByYearClass = studentHaveDutyByYearClass;
		this.canDo = canDo;
		this.averagePerQuarter = averagePerQuarter;
		this.status = status;
		this.activities = activities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "quarter_id", nullable = false)
	public Quarter getQuarter() {
		return this.quarter;
	}

	public void setQuarter(Quarter quarter) {
		this.quarter = quarter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_have_duty_by_year_class_id", nullable = false)
	public StudentHaveDutyByYearClass getStudentHaveDutyByYearClass() {
		return this.studentHaveDutyByYearClass;
	}

	public void setStudentHaveDutyByYearClass(StudentHaveDutyByYearClass studentHaveDutyByYearClass) {
		this.studentHaveDutyByYearClass = studentHaveDutyByYearClass;
	}

	@Column(name = "can_do")
	public Integer getCanDo() {
		return this.canDo;
	}

	public void setCanDo(Integer canDo) {
		this.canDo = canDo;
	}

	@Column(name = "average_per_quarter")
	public Integer getAveragePerQuarter() {
		return this.averagePerQuarter;
	}

	public void setAveragePerQuarter(Integer averagePerQuarter) {
		this.averagePerQuarter = averagePerQuarter;
	}

	@Column(name = "status", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studentHaveDutyByYearClassQuarter")
	public Set<Activitie> getActivities() {
		return this.activities;
	}

	public void setActivities(Set<Activitie> activities) {
		this.activities = activities;
	}

}
