package PIM.WEBSERIVE.ACTIVITIE.STUDENT.Model;
// default package
// Generated 22 �.�. 2561, 22:56:21 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * StudentHaveDuty generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "student_have_duty", catalog = "panyapiway_student_activitie")
public class StudentHaveDuty implements java.io.Serializable {

	private long id;
	@JsonSerialize(as = Duty.class)
	private Duty duty;
	@JsonSerialize(as = Student.class)
	private Student student;
	@JsonIgnore
	private Set<StudentHaveDutyByYearClass> studentHaveDutyByYearClasses = new HashSet<StudentHaveDutyByYearClass>(0);

	public StudentHaveDuty() {
	}

	public StudentHaveDuty(long id, Duty duty, Student student) {
		this.id = id;
		this.duty = duty;
		this.student = student;
	}

	public StudentHaveDuty(long id, Duty duty, Student student,
			Set<StudentHaveDutyByYearClass> studentHaveDutyByYearClasses) {
		this.id = id;
		this.duty = duty;
		this.student = student;
		this.studentHaveDutyByYearClasses = studentHaveDutyByYearClasses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "duty_id", nullable = false)
	public Duty getDuty() {
		return this.duty;
	}

	public void setDuty(Duty duty) {
		this.duty = duty;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id", nullable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studentHaveDuty")
	public Set<StudentHaveDutyByYearClass> getStudentHaveDutyByYearClasses() {
		return this.studentHaveDutyByYearClasses;
	}

	public void setStudentHaveDutyByYearClasses(Set<StudentHaveDutyByYearClass> studentHaveDutyByYearClasses) {
		this.studentHaveDutyByYearClasses = studentHaveDutyByYearClasses;
	}

}
