package PIM.WEBSERIVE.ACTIVITIE.STUDENT.Model;
// default package
// Generated 22 �.�. 2561, 22:56:21 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * StudentHaveDutyByYearClass generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "student_have_duty_by_year_class", catalog = "panyapiway_student_activitie")
public class StudentHaveDutyByYearClass implements java.io.Serializable {

	private Long id;
	@JsonSerialize(as = StudentHaveDuty.class)
	private StudentHaveDuty studentHaveDuty;
	@JsonSerialize(as = YearClass.class)
	private YearClass yearClass;
	private Integer limitPerStudyLevel;
	private String status;
	@JsonIgnore
	private Set<StudentHaveDutyByYearClassQuarter> studentHaveDutyByYearClassQuarters = new HashSet<StudentHaveDutyByYearClassQuarter>(
			0);

	public StudentHaveDutyByYearClass() {
	}

	public StudentHaveDutyByYearClass(StudentHaveDuty studentHaveDuty, YearClass yearClass) {
		this.studentHaveDuty = studentHaveDuty;
		this.yearClass = yearClass;
	}

	public StudentHaveDutyByYearClass(StudentHaveDuty studentHaveDuty, YearClass yearClass, Integer limitPerStudyLevel,
			String status, Set<StudentHaveDutyByYearClassQuarter> studentHaveDutyByYearClassQuarters) {
		this.studentHaveDuty = studentHaveDuty;
		this.yearClass = yearClass;
		this.limitPerStudyLevel = limitPerStudyLevel;
		this.status = status;
		this.studentHaveDutyByYearClassQuarters = studentHaveDutyByYearClassQuarters;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_have_duty_id", nullable = false)
	public StudentHaveDuty getStudentHaveDuty() {
		return this.studentHaveDuty;
	}

	public void setStudentHaveDuty(StudentHaveDuty studentHaveDuty) {
		this.studentHaveDuty = studentHaveDuty;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "year_class_id", nullable = false)
	public YearClass getYearClass() {
		return this.yearClass;
	}

	public void setYearClass(YearClass yearClass) {
		this.yearClass = yearClass;
	}

	@Column(name = "limit_per_study_level")
	public Integer getLimitPerStudyLevel() {
		return this.limitPerStudyLevel;
	}

	public void setLimitPerStudyLevel(Integer limitPerStudyLevel) {
		this.limitPerStudyLevel = limitPerStudyLevel;
	}

	@Column(name = "status", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studentHaveDutyByYearClass")
	public Set<StudentHaveDutyByYearClassQuarter> getStudentHaveDutyByYearClassQuarters() {
		return this.studentHaveDutyByYearClassQuarters;
	}

	public void setStudentHaveDutyByYearClassQuarters(
			Set<StudentHaveDutyByYearClassQuarter> studentHaveDutyByYearClassQuarters) {
		this.studentHaveDutyByYearClassQuarters = studentHaveDutyByYearClassQuarters;
	}

}
